config/routes.rb
Rails.application.routes.draw do

  get '/users/search' => 'users#search'
  get '/samples/compare' => 'samples#compare'
  get '/keywords/compare' => 'keywords#compare'
  get '/samples/new_multiple' => 'samples#new_multiple'

  resources :users, only: [:new, :create, :edit, :update]

  resources :samples, except: [:edit, :update]
  post 'analyze' => 'samples#analyze', as: :analyze
  post 'analyze_multiple' => 'samples#analyze_multiple', as: :analyze_multiple

  resources :reports, except: [:edit, :update]

  resources :users

  resources :tweets

  resources :keywords, only: [:create, :update]

  get '/tweets/get_username' => 'tweets#get_username'
  get '/samples/get_username' => 'samples#get_username'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  root 'welcome#index'

end

app/models/keyword.rb
class Keyword < ActiveRecord::Base
  belongs_to :sample
end

app/models/sample.rb
class Sample < ActiveRecord::Base
	belongs_to :user
  has_many :keywords
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :samples
  has_many :keywords, through: :samples

  validates :email, presence: true, uniqueness: true

	has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
	
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController
  def update
    keyword = Keyword.find_by(id: params[:id])
    keyword.gender = params[:gender]
    keyword.save
    head :ok
  end

  def compare
  end
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController

  def new
  end

  def analyze
    caller = APICoordinator.new(params)
    caller.call_API
    sample = caller.create_sample
    if sample
      keywords = caller.create_keywords
      sample.user_id = session[:user_id]
      sample.save
      render json: { sample: sample, keywords: keywords },
      :status => 200
    else
      render json: "Our system did not find any text that it could analyze on that page.", :status => :bad_request
    end

  end

  def show
    sample = Sample.find_by(id: params[:id])
    render json: { sample: sample,
      keywords: sample.keywords }
  end

  def analyze_multiple
    urls = params[:url][:url].split(',')
    urls.each do |url|
      caller = APICoordinator.new({url: {url: url, name: params[:url][:name]}})
      caller.call_API
      sample = caller.create_sample
      keywords = caller.create_keywords
      sample.user_id = session[:user_id]
      sample.save
    end
    render json: {message: "Your samples were saved."}
  end


  def new
  end

  def destroy
    @sample = Sample.find(params[:id])
    @sample.destroy
    @sample.keywords.destroy_all
    head :ok
    # if current_user
    #   redirect_to user_path(current_user.id)
    # else
    #   redirect_to root_path
    # end
  end

  def compare
    user = User.find_by(id: session[:user_id])
    respond_to do |format|
      format.html
      format.json { render json: { samples: user.samples, keywords: user.keywords }}
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render 'users/login'
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to "/"
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'users/login'
    end
  end

  def destroy
    session.clear
    redirect_to "/"
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    redirect_to '/'
  end

  def search
    user = User.find(session[:user_id])
    query = params[:query].downcase
    @sample_matches = []
    key_matches = []
    @frequency = Hash.new(0)

    user.samples.each do |sample|
      if sample.keywords.any?
        sample.keywords.each do |keyword|
          key_matches << keyword
        end
      end
    end

    @key_matches = key_matches.select {|key| key.text.downcase.match(/(#{query})/)}
    @key_matches.each {|key| @sample_matches << key.sample}
    @sample_matches.uniq!

    @key_matches.each do |key|
      sample_data = key.sample.content.split(" ")
      sample_data.each do |word|
        if word == key.text.split(" ")[0]
          @frequency[key.text] += 1
        end
      end
    end
    # returns @frequency hash, @sample_matches array of matched samples to keys, and @key_matches to the user's query
  end

  def show
    # binding.pry
    if logged_in?
      @user = User.find(params[:id])
      respond_to do |format|
        format.html {}
        format.js {}
        format.json { render :json => {samples: @user.samples, keywords: @user.keywords}.to_json }
      end
    else
      redirect_to '/'
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/'
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user
    else
      redirect_to @user
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash.notice = "#{@user.name} has been destroyed."
    redirect_to '/'
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def logged_in?
    current_user != nil
  end
  
end

app/helpers/samples_helper.rb
module SamplesHelper
  def markup_keywords(sample)
    sample.content
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjectZe</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js">
  </script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous">
  </script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.min.js"></script>
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/c3/0.4.10/c3.min.css">
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/c3/0.4.10/c3.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default">
    <div class="container-fluid">

      <div class="navbar-left-pos" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-left">
          <li>
            <%= link_to 'ProjectZe', '/' %>
          </li>
        </ul>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
          <li><form action="/users/search" class="search-form">
            <input name="query" placeholder="search keywords">
          </form></li>
          <li><%= link_to "Create new sample", new_sample_path %></li>
          <li><%= link_to current_user.email, user_path(current_user), remote: true, "data-type" => "json", id: "profile" %></li>
          <li><%= link_to 'Logout', logout_path, method: :delete %></li>
          <% else %>
          <li><%= link_to 'Register', new_user_path %></li>
          <li><%= link_to 'Login', login_path %></li>
          <% end %>
        </ul>
      </div>

    </div>
  </nav>


  <div id="content" class="container">
    <%= yield %>
  </div>



</body>


</html>

app/views/samples/compare.html.erb
<h3>Compare Engine</h3>

<%= link_to("Build keywords pivot", samples_compare_path, remote: true, class: "compare", "data-type" => "json") %>

<div id="pivot"></div>

app/views/samples/new.html.erb
<h2 class="new-sample-title">Analyze Data</h2>

<div id="sample-form-container">
	<div id="toggle-form">
		<ul>
			<li><a href="#text_form">Enter Text</a></li>
			<li><a href="#twitter_form">Scrape Twitter</a></li>
			<li><a href="#drop_form">Upload a File</a></li>
			<li><a href="#url_form">Provide Url</a></li>
			<li><a href="#multiple_url_form">Multiple Urls</a></li>
			<!-- <li><a href="#image_form">Image OCR</a></li> -->
			<span title="These options let you choose what format of text you would like to analyze." class=" tool-popup tool-popup-icon">?</span>
		</ul>
	</div>

	<div id="text_form">
		<%= form_for :sample, {url: analyze_path, remote: true, html: { class: "content-input text-box" } } do |f| %>
		<%= f.text_field :name, :placeholder => "Sample name", id: 'text_sample_name'  %>
		<br>
		<br>
		<%= f.text_area :content, :placeholder => "Sample text" %>
		<br>
		<%= f.submit "Analyze!" %>
		<% end %>
	</div>

	<div id="twitter_form">
		<%= form_for :tweet, {url: analyze_path, remote: true, html: { class: "content-input text-box", autocomplete: "off" } } do |f| %>
		<%= f.text_field :name, :placeholder => "Sample name"  %>
		<br>
		<br>
		<%= f.text_field :content, :placeholder => "Twitter handle" %>
		<br>
		<%= f.submit "Analyze", :class => 'twitter-submit-button' %>
		<% end %>
	</div>

	<div id="url_form">

		<%= form_for :url, {url: analyze_path, remote: true, html: { class: "content-input text-box" } } do |f| %>
		<%= f.text_field :name, :placeholder => "Sample name", id: 'url_sample_name'  %>
		<br>
		<br>
		<%= f.text_field :url, :placeholder => "URL" %>
		<br>
		<%= f.submit "Analyze", :class => 'twitter-submit-button' %>
		<% end %>
	</div>

  <div id="multiple_url_form">
    <%= form_for :url, {url: analyze_multiple_path, remote: true, html: { class: "text-box" } } do |f| %>
    <%= f.text_field :name, :placeholder => "Name for all samples", id: 'url_sample_name'  %>
    <br>
    <br>
    <%= f.text_field :url, :placeholder => "Enter multiple, comma-separated URLs" %>
    <br>
    <%= f.submit "Analyze", :class => 'twitter-submit-button' %>
    <% end %>
    <div id="multiple-url-messages"></div>
  </div>

	<div id="drop_form">
		<%= form_tag({action: :analyze}, {multipart: true, class: "dropzone content-input", id:"drop-form"}) do %>
		<% end %>
	</div>

	<div id="image_form">
		<%= form_for :image, {url: analyze_path, multipart: true, authenticity_token: true, html: { id: "image_submit" } } do |f| %>
		  <%= f.label "Upload an image"  %>
		  <%= f.file_field :filename %>
		  <%= f.submit "Submit", id: "submit_image" %>
		<% end %>
	</div>
</div>



<div id="output">
	<div id="averages"></div>
	<div id="highlighted-text"></div>
	<div id="number-line"></div>
	<div id="error"></div>
</div>

app/views/samples/show.html.erb
<h1>Sample page</h1>

app/views/tweets/new.html.erb
<h1>Analyze tweets</h1>

<form action="/tweets/get_username" method="GET">
  <label>Username:</label>
  <input type="text" name="username">
  <input type="submit">
</form>

app/views/tweets/show.html.erb
<% @tweet_objects.each do |tweet| %>
  <li> <%= tweet.text  %> </li>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

  <% if @user.errors.any? %>
    <div>
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this user from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/users/edit.html.erb
<%= link_to "Back to Home", '/' %>

<h1>Edit Your Profile:</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<div>
	<%= link_to "Back to Home", '/' %>
</div>

<div>
	<ul>
	  <% @users.each do |user| %>
	    <li>
	      <%= link_to user.email, user_path(user)  %>
	    </li>
	  <% end %>
	</ul>
</div>

app/views/users/login.html.erb
<% if flash[:danger] %>
  <div class="danger"><%= flash[:danger] %></div>
<% end %>

<%= form_tag '/login', method: :post, id: "login-form" do %>
  <p>
    <%= label_tag :email %><br>
    <%= text_field_tag :email %>
  </p>

  <p>
    <%= label_tag :password %><br>
    <%= password_field_tag :password %>
  </p>

  <p>
    <%= submit_tag "Login" %>
  </p>

<% end %>

app/views/users/new.html.erb
<h1>Create an Account:</h1>

<%= render 'form' %>

app/views/users/search.html.erb
<h3>Query Results</h3> 
<hr>
<div class="frequecy-container">
	<h3>Word Frequency <span class="tool-popup tool-popup-icon" title="This shows the frequency of the key in all of your samples">?</span></h3>
	<table class="frequency-table">
		<tr>
			<th><strong>Key Word</strong></th>
			<th><strong>Frequency</strong></th>
		</tr>

		<% @frequency.each do |key,val| %>
		<tr>
			<td class="key"><%= key %></td>
			<td><%= val %></td>
		</tr>
		<% end %>
	</table>
</div>

<div class="samples-container">
	<h3>Samples: <span class="tool-popup tool-popup-icon" title="Samples display their marked-up content along with their sentiment keys, values, and corresponding sample content">?</span></h3>
	<ul>
		<% @sample_matches.each do |sample| %>
	<li>
			<h3><%= sample.name %></h3>
			<p class="sample-content"><%= sample.content %></p>
			
			<table class="keyword-table">
				<tr>
					<th><strong>Key</strong></th>
					<th><strong>Score</strong></th>
					<th><strong>Type</strong></th>
					<th><strong>Gender</strong></th>
				</tr>
			<% @key_matches.each do |s| %>
			<% if s.sample_id == sample.id %>

				<tr>
					<td><%= s.text %></td>
					<td><%= s.sentiment_score %></td>
					<td><%= s.sentiment_type %></td>
					<td><%= s.gender %></td>
				</tr>
			<% end %>
			<% end %>
			</table>
			<hr>
			<% end %>
		</li>
	</ul>
</div>

app/views/users/show.html.erb
<%= link_to "Back to Home", '/' %><br>

<% if current_user == @user %>
<%= link_to "Edit Profile", edit_user_path(@user) %><br>
<% end %>

<% if logged_in? %>
<h1><%= @user.email %></h1>
<% end %>

<form action="/users/search">
	<input name="query" placeholder="search keywords">
</form>

<%= link_to("Generate sample scatter", user_path(@user), remote: true, "data-type" => "json", id: "scatter-link")  %>

<div id="scatter">
</div>

<ul>
	<% @user.samples.each do |sample| %>

	<li><%= sample.content %></li>

	<% end %>
</ul>

app/views/welcome/index.html.erb
<div class="logo container">
	<h1>ProjectZe</h1>
</div>

<div class="container index-info">
	<p>This site is designed to analyze text for sentiment and bias towards a particular gender.</p>
</div>

<div class="create-sample-button-wrapper">
	<div class="create-sample-button btn-default">
		<%= link_to "Get Started", new_sample_path %>
	</div>
</div>